# Generated by Django 2.1.7 on 2019-04-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('keywords', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Domains')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Network')),
            ],
            options={
                'ordering': ('network',),
            },
        ),
        migrations.AddField(
            model_name='network',
            name='domains',
            field=models.ManyToManyField(through='network.Relation', to='start.Domains'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('network', 'domain')},
        ),
    ]
