# Generated by Django 2.1.7 on 2019-04-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20190413_2348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='relation',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='network',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
