# Generated by Django 2.1.2 on 2018-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='source_url',
            new_name='impressum_url',
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
