# Generated by Django 2.1.2 on 2018-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20181128_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='plz',
            field=models.SmallIntegerField(null=True),
        ),
    ]
