# Generated by Django 2.1.2 on 2018-12-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_info_plz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='plz',
            new_name='zip',
        ),
    ]
