# Generated by Django 2.1.2 on 2018-12-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_auto_20181203_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='src_domain',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
