# Generated by Django 2.1.2 on 2018-12-26 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_domains_src_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
