# Generated by Django 2.1.2 on 2018-12-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_auto_20181226_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='fullsan',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
