# Generated by Django 2.1.2 on 2018-12-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0007_domains_fullsan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domains',
            old_name='fullsan',
            new_name='fullscan',
        ),
        migrations.AddField(
            model_name='externals',
            name='selected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
