# Generated by Django 2.1.2 on 2019-01-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0008_auto_20181231_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externals',
            name='selected',
        ),
    ]
