# Generated by Django 2.1.2 on 2019-01-12 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0009_remove_externals_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalIgnore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_ignore', models.TextField(max_length=200, unique=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_ignore', to='start.Domains')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='localignore',
            unique_together={('local_ignore', 'domain')},
        ),
    ]
