# Generated by Django 2.1.7 on 2019-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0011_auto_20190121_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='status',
            field=models.CharField(default='created', max_length=10),
        ),
    ]
