# Generated by Django 2.1.7 on 2019-04-01 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0012_auto_20190401_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spiders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80)),
                ('job_id', models.CharField(max_length=80)),
                ('duration', models.DurationField(default=datetime.timedelta(0), null=True)),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spiders', to='start.Domains')),
            ],
            options={
                'ordering': ('domain',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='spiders',
            unique_together={('name', 'domain')},
        ),
    ]
