# Generated by Django 2.1.7 on 2019-04-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0013_auto_20190401_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='externalscan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='domains',
            name='infoscan',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
