# Generated by Django 2.1.7 on 2019-04-02 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0014_auto_20190401_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=80)),
                ('duration', models.DurationField(default=datetime.timedelta(0), null=True)),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='externalspider', to='start.Domains')),
            ],
        ),
        migrations.CreateModel(
            name='InfoSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=80)),
                ('duration', models.DurationField(default=datetime.timedelta(0), null=True)),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infospider', to='start.Domains')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='spiders',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='spiders',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Spiders',
        ),
    ]
