# Generated by Django 2.1.7 on 2019-04-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0015_auto_20190402_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalspider',
            name='to_scan',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='infospider',
            name='to_scan',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
