# Generated by Django 2.1.7 on 2019-04-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0016_auto_20190402_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='other',
            new_name='misc',
        ),
        migrations.RemoveField(
            model_name='info',
            name='impressum_url',
        ),
        migrations.RemoveField(
            model_name='info',
            name='name',
        ),
        migrations.AddField(
            model_name='externalspider',
            name='log_error_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='externalspider',
            name='request_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='externalspider',
            name='robots_forbidden',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='desc',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='imprint',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='keywords',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='tip',
            field=models.CharField(default='no suggestions', max_length=100),
        ),
        migrations.AddField(
            model_name='infospider',
            name='log_error_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='infospider',
            name='request_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='infospider',
            name='robots_forbidden',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
