# Generated by Django 2.1.7 on 2019-04-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0017_auto_20190403_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='tip',
            field=models.CharField(default='no suggestions', max_length=100, null=True),
        ),
    ]
