# Generated by Django 2.1.7 on 2019-04-04 08:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0018_auto_20190403_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalspider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('81fa22b2-56b3-11e9-be45-8c85908458e4'), max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='infospider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('81fa3ff4-56b3-11e9-be45-8c85908458e4'), max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='externalspider',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalspider', to='start.Domains'),
        ),
        migrations.AlterField(
            model_name='infospider',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infospider', to='start.Domains'),
        ),
        migrations.RemoveField(
            model_name='externalspider',
            name='job_id',
        ),
        migrations.AlterUniqueTogether(
            name='externalspider',
            unique_together={('unique_id', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='infospider',
            unique_together={('unique_id', 'domain')},
        ),
    ]
