# Generated by Django 2.1.7 on 2019-04-04 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0019_auto_20190404_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalspider',
            name='job_id',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='externalspider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('8e5ad136-56b4-11e9-a010-8c85908458e4'), max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='infospider',
            name='job_id',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='infospider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('8e5aec7a-56b4-11e9-a010-8c85908458e4'), max_length=128, unique=True),
        ),
    ]
