# Generated by Django 2.1.7 on 2019-04-04 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0022_auto_20190404_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalspider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('594acc30-56f0-11e9-b236-8c85908458e4'), max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='infospider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('594ae47c-56f0-11e9-b236-8c85908458e4'), max_length=128, unique=True),
        ),
    ]
