# Generated by Django 2.1.7 on 2019-04-04 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0023_auto_20190404_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalspider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('74f34502-56f0-11e9-a1cd-8c85908458e4'), max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='infospider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('74f35aba-56f0-11e9-a1cd-8c85908458e4'), max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='externalspider',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='infospider',
            unique_together=set(),
        ),
    ]
