# Generated by Django 2.1.7 on 2019-04-04 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0024_auto_20190404_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalspider',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='externalspider', to='start.Domains'),
        ),
        migrations.AlterField(
            model_name='externalspider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('045c1276-56f3-11e9-8927-8c85908458e4'), max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='infospider',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infospider', to='start.Domains'),
        ),
        migrations.AlterField(
            model_name='infospider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('045c2e96-56f3-11e9-8927-8c85908458e4'), max_length=128, unique=True),
        ),
    ]
