# Generated by Django 2.1.7 on 2019-04-04 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0025_auto_20190404_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalspider',
            old_name='finished',
            new_name='finish',
        ),
        migrations.RenameField(
            model_name='externalspider',
            old_name='started',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='infospider',
            old_name='finished',
            new_name='finish',
        ),
        migrations.RenameField(
            model_name='infospider',
            old_name='started',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='externalspider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('dbd637f0-56f7-11e9-895f-8c85908458e4'), max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='infospider',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('dbd65d2a-56f7-11e9-895f-8c85908458e4'), max_length=128, unique=True),
        ),
    ]
