# Generated by Django 2.1.7 on 2019-04-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0026_auto_20190404_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalspider',
            old_name='status',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='infospider',
            old_name='name',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='externalspider',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='infospider',
            name='status',
        ),
        migrations.RemoveField(
            model_name='infospider',
            name='unique_id',
        ),
    ]
