# Generated by Django 2.1.7 on 2019-04-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0028_info_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='duration',
        ),
        migrations.AlterField(
            model_name='externalspider',
            name='start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='infospider',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
