# Generated by Django 2.1.7 on 2019-04-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0029_auto_20190405_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='desc',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
