# Generated by Django 2.1.7 on 2019-04-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0030_auto_20190405_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='src_domain',
            field=models.TextField(default='manual', max_length=200, null=True),
        ),
    ]
