# Generated by Django 2.1.7 on 2019-04-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore', models.TextField(max_length=200, unique=True)),
                ('src_domain', models.TextField(max_length=200)),
            ],
        ),
    ]
